# Generated by Django 5.0.1 on 2024-01-26 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notices', '0002_remove_notice_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='verb',
            new_name='content_text',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='sender',
        ),
        migrations.AddField(
            model_name='notice',
            name='content_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
