# Generated by Django 5.0.1 on 2024-02-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
