# Generated by Django 5.0.1 on 2024-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evendy', '0008_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=models.SET(None), related_name='receiver', to='evendy.profile')),
                ('sender', models.ForeignKey(on_delete=models.SET(None), related_name='sender', to='evendy.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, unique=True)),
                ('receiver', models.ForeignKey(on_delete=models.SET(None), related_name='room_receiver', to='evendy.profile')),
                ('sender', models.ForeignKey(on_delete=models.SET(None), related_name='room_sender', to='evendy.profile')),
            ],
        ),
    ]
