# Generated by Django 5.0.1 on 2024-02-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evendy', '0001_initial'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_invitations',
            field=models.ManyToManyField(blank=True, related_name='user_invitations', to='notices.invitation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_notices',
            field=models.ManyToManyField(blank=True, related_name='user_notices', to='notices.notice'),
        ),
        migrations.AddField(
            model_name='eventcouple',
            name='profiles',
            field=models.ManyToManyField(to='evendy.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees_looking_for_company',
            field=models.ManyToManyField(related_name='events_who_is_looking_for_company', to='evendy.profile'),
        ),
        migrations.AddField(
            model_name='userplannedevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evendy.event'),
        ),
        migrations.AddField(
            model_name='userplannedevent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evendy.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_planned_events',
            field=models.ManyToManyField(through='evendy.UserPlannedEvent', to='evendy.event'),
        ),
    ]
