# Generated by Django 5.0.1 on 2024-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_pics/event_default.jpg', upload_to='event_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_pics/profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
