# Generated by Django 5.0.1 on 2024-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0002_alter_event_image_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
