# Generated by Django 5.0.1 on 2024-02-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
