# Generated by Django 5.0.1 on 2024-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0003_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
