# Generated by Django 5.0.1 on 2024-02-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
