# Generated by Django 5.0.1 on 2024-01-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0004_profile_description_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_looking_for_company',
            field=models.ManyToManyField(related_name='events_who_is_looking_for_company', to='evendy.profile'),
        ),
    ]
