# Generated by Django 5.0.1 on 2024-01-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0005_event_attendees_looking_for_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.JSONField(),
        ),
    ]
