# Generated by Django 5.0.1 on 2024-01-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0005_event_attendees_looking_for_company'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_invitations',
            field=models.ManyToManyField(blank=True, related_name='user_invitations', to='notices.invitation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_notices',
            field=models.ManyToManyField(blank=True, related_name='user_notices', to='notices.notice'),
        ),
    ]
