# Generated by Django 5.0.1 on 2024-01-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0006_alter_event_time_invitation'),
        ('evendy', '0006_profile_user_invitations_profile_user_notices'),
    ]

    operations = [
    ]
