# Generated by Django 5.0.1 on 2024-01-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0007_merge_20240126_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
