# Generated by Django 5.0.1 on 2024-01-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0008_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sender',
        ),
    ]
