# Generated by Django 5.0.1 on 2024-02-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0008_delete_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCouple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evendy.event')),
                ('profiles', models.ManyToManyField(limit_choices_to=2, to='evendy.profile')),
            ],
        ),
    ]
