# Generated by Django 5.0.1 on 2024-01-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0008_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
