# Generated by Django 5.0.1 on 2024-02-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0009_eventcouple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcouple',
            name='profiles',
            field=models.ManyToManyField(to='evendy.profile'),
        ),
    ]
