# Generated by Django 5.0.1 on 2024-01-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0009_remove_invitation_event_remove_invitation_recipient_and_more'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_invitations',
            field=models.ManyToManyField(blank=True, related_name='user_invitations', to='notices.invitation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_notices',
            field=models.ManyToManyField(blank=True, related_name='user_notices', to='notices.notice'),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
