# Generated by Django 5.0.1 on 2024-01-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evendy', '0010_invitation_profile_user_invitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
    ]
